routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PengirimanController;
use App\Http\Controllers\ProjectsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');



require __DIR__.'/auth.php';

Route::resource('pengirimans', PengirimanController::class);
Route::resource('projects', ProjectsController::class);

resources/views/projectlist/create.blade.php
@extends('layouts.home')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add new</h2>
            </div>
        </div>
    </div>
    <br>  
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
        
    <form action="{{ route('projects.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>No Projek</strong>
                    <input type="number" name="no_projek" class="form-control" placeholder="No Projek">
                </div>
                <div class="form-group">
                    <strong>No SPK</strong>
                    <input type="number" name="no_spk" class="form-control" placeholder="No SPK">
                </div>
                <div class="form-group">
                    <strong>Costumer</strong>
                    <input type="text" name="costumer" class="form-control" placeholder="Costumer">
                </div>
                <div class="form-group">
                    <strong>Nama Projek</strong>
                    <input type="text" name="nama_projek" class="form-control" placeholder="Nama Projek">
                </div>
                <div class="form-group">
                    <strong>Tanggal Mulai</strong>
                    <input type="date" name="tanggal_mulai" class="form-control" placeholder="Tanggal Mulai">
                </div>
                <div class="form-group">
                    <strong>Tanggal Akhir</strong>
                    <input type="date" name="tanggal_akhir" class="form-control" placeholder="Tanggal Akhir">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-danger" href="{{ route('projects.index') }}"> Back</a>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
        
    </form>
@endsection

resources/views/projectlist/edit.blade.php
@extends('layouts.home')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit</h2>
            </div>
        </div>
    </div>
    <br>  
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
        
    <form action="{{ route('projects.update', $project->id) }}" method="POST" enctype="multipart/form-data"> 
        @csrf

        @method('PUT')
        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>No Projek</strong>
                    <input type="number" name="no_projek" class="form-control" placeholder="No Projek" value="{{$project->no_projek}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>No SPK</strong>
                    <input type="number" name="no_spk" class="form-control" placeholder="No SPK" value="{{$project->no_spk}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Costumer</strong>
                    <input type="text" name="costumer" class="form-control" placeholder="Costumer" value="{{$project->costumer}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Nama Projek</strong>
                    <input type="text" name="nama_projek" class="form-control" placeholder="Nama Projek" value="{{$project->nama_projek}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Tanggal Mulai</strong>
                    <input type="date" name="tanggal_mulai" class="form-control" placeholder="Tanggal Mulai" value="{{$project->tanggal_mulai}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Tanggal Akhir</strong>
                    <input type="date" name="tanggal_akhir" class="form-control" placeholder="Tanggal Akhir" value="{{$project->tanggal_akhir}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-danger" href="{{ route('projects.index') }}"> Back</a>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
        
    </form>
@endsection

resources/views/projectlist/index.blade.php
@extends('layouts.home')

@section('styles')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">  
@endsection

@section('content')

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Daftar projek</h1>
        <a href="{{ route('projects.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Tambah projek</a>
    </div>
    <br>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Table projek</h6>
        </div>
        <div class="card-body">
            <table class="display table" id="table_id" width="100%">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>No Projek</th>
                        <th>No SPK</th>
                        <th>Costumer</th>
                        <th>Nama Projek</th>
                        <th>Tanggal Mulai</th>
                        <th>Tanggal Akhir</th>
                        <th>action</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($projects as $project)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $project->no_projek }}</td>
                        <td>{{ $project->no_spk}}</td>
                        <td>{{ $project->costumer }}</td>
                        <td>{{ $project->nama_projek }}</td>
                        <td>{{ $project->tanggal_mulai }}</td>
                        <td>{{ $project->tanggal_akhir }}</td>
                        <td>
                            <a class="btn btn-circle btn-primary" href="{{ route('projects.edit',$project->id) }}">
                                <i class="fas fa-edit fa-md"></i></a>
                        </td>
                        <td>
                            <button type="submit" class="btn btn-circle btn-danger" data-toggle="modal" data-target="#deleteModal">
                                <i class="fas fa-trash fa-md"></i></button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- Delete Modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin ingin menghapus data ini</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Anda tidak akan bisa memulihkan kembali data ini</div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="button" data-dismiss="modal">Cancel</button>
                    @foreach ($projects as $project)
                        <form action="{{ route('projects.destroy',$project->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            @endforeach
                            <button type="submit" class="btn btn-danger">
                                Delete
                            </button>
                        </form>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('javascripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection