routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PengirimanController;
use App\Http\Controllers\ProjectsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');



require __DIR__.'/auth.php';

Route::resource('pengirimans', PengirimanController::class);
Route::resource('projects', ProjectsController::class);

app/Models/Pengiriman.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengiriman extends Model
{
    use HasFactory;

    protected $table = 'invoices';
    protected $fillable = [
        'tanggal_invoice', 'tanggal_kirim', 'costumer', 
        'nama_projek', 'no_invoice', 'no_faktur',
        'termin', 'nominal_projek', 'ppn',
        'total_invoice', 'keterangan', 'pembayaran'
    ];
}

app/Http/Controllers/PengirimanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pengiriman;
use App\Models\Project;
use Illuminate\Http\Request;
use Alert;

class PengirimanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengirimans = Pengiriman::all();

        return view('pengirimans.index',compact('pengirimans'))
            ->with('i', (request()->input('page', 1) - 1) * 5);   
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $products = Project::all();
        return view('pengirimans.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'tanggal_invoice' => 'required', 
            'tanggal_kirim' => 'required', 
            'costumer' => 'required', 
            'nama_projek' => 'required', 
            'no_invoice' => 'required', 
            'no_faktur' => 'required',
            'termin' => 'required', 
            'nominal_projek' => 'required', 
            'ppn' => 'required',
            'total_invoice' => 'required', 
            'keterangan' => 'required', 
            'pembayaran' => 'required',
        ]);

        Pengiriman::create($request->all());
        toast('Berhasil menambah!','success');
        return redirect()->route('pengirimans.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pengiriman  $pengiriman
     * @return \Illuminate\Http\Response
     */
    public function show(Pengiriman $pengiriman)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pengiriman  $pengiriman
     * @return \Illuminate\Http\Response
     */
    public function edit(Pengiriman $pengiriman)
    {   
        $products = Project::all();
        return view('pengirimans.edit',compact('pengiriman', 'products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pengiriman  $pengiriman
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pengiriman $pengiriman)
    {
        $request->validate([
            'tanggal_invoice' => 'required', 
            'tanggal_kirim' => 'required', 
            'costumer' => 'required', 
            'nama_projek' => 'required', 
            'no_invoice' => 'required', 
            'no_faktur' => 'required',
            'termin' => 'required', 
            'nominal_projek' => 'required', 
            'ppn' => 'required',
            'total_invoice' => 'required', 
            'keterangan' => 'required', 
            'pembayaran' => 'required',
        ]);

        $pengiriman->update($request->all());
        toast('Berhasil mengubah!','success');
        return redirect()->route('pengirimans.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pengiriman  $pengiriman
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pengiriman $pengiriman)
    {
        $pengiriman->delete();

        toast('Berhasil mengahapus!','success');
        return redirect()->route('pengirimans.index');
    }
}

resources/views/pengirimans/create.blade.php
@extends('layouts.home')

@section('content')
{{-- @dump(get_defined_vars()) --}}
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add new</h2>
            </div>
        </div>
    </div>
    <br>  
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form action="{{ route('pengirimans.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Tanggal Invoice</strong>
                    <input type="date" name="tanggal_invoice" class="form-control" placeholder="Tanggal Invoice">
                </div>
                <div class="form-group">
                    <strong>Nama Projek</strong>
                    <select class="form-control" name="nama_projek" id="namaProjek">
                        @foreach($products as $product)
                            <option value="{{$product->nama_projek}}" data-costumer="{{$product->costumer}}">{{$product->nama_projek}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <strong>No Invoice</strong>
                    <input type="number" name="no_invoice" class="form-control" placeholder="No Invoice">
                </div>
                <div class="form-group">
                    <strong>Termin</strong>
                    <input type="number" name="termin" class="form-control" placeholder="Termin">
                </div>
                <div class="form-group">
                    <strong>Nominal</strong>
                    <input type="number" name="nominal_projek" class="form-control" placeholder="Nominal">
                </div>
                <div class="form-group">
                    <strong>Keterangan</strong>
                    <input type="date" name="keterangan" class="form-control" placeholder="Keterangan">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Tanggal Kirim</strong>
                    <input type="date" name="tanggal_kirim" class="form-control" placeholder="Tanggal Kirim">
                </div>
                <div class="form-group">
                    <strong>Costumer</strong>
                    <input type="text" name="costumer" class="form-control" placeholder="costumer" id="costumersInput" readonly>
                </div>
                <div class="form-group">
                    <strong>No Faktur</strong>
                    <input type="number" name="no_faktur" class="form-control" placeholder="No Faktur">
                </div>
                <div class="form-group">
                    <strong>Total Invoice</strong>
                    <input type="number" name="total_invoice" class="form-control" placeholder="Total Invoice">
                </div>
                <div class="form-group">
                    <strong>PPN</strong>
                    <input type="number" name="ppn" class="form-control" placeholder="PPN">
                </div>
                <div class="form-group">
                    <strong>Pembayaran</strong>
                    <input type='currency' name="pembayaran" class="form-control" placeholder="Pembayaran">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-danger" href="{{ route('pengirimans.index') }}"> Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

@section('javascripts')
    <script>
        // code untuk mengisi collum costumer
        // saat memilih project
        let namaProjek = document.getElementById('namaProjek');
        let costumersInput = document.getElementById('costumersInput');

        namaProjek.addEventListener('change', (e) => {
            // console.log( namaProjek.options[namaProjek.selectedIndex].dataset);
            let costumer = namaProjek.options[namaProjek.selectedIndex].dataset.costumer;
            costumersInput.value=costumer;
        })
    </script>
@endsection

resources/views/pengirimans/edit.blade.php
@extends('layouts.home')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit</h2>
            </div>
        </div>
    </div>
    <br>  
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
        
    <form action="{{ route('pengirimans.update',$pengiriman->id) }}" method="POST" enctype="multipart/form-data"> 
        @csrf

        @method('PUT')
        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Tanggal Invoice</strong>
                    <input type="date" name="tanggal_invoice" class="form-control" placeholder="Tanggal Invoice" value="{{$pengiriman->tanggal_invoice}}">
                </div>
                <div class="form-group">
                    <strong>Nama Projek</strong>
                    <select class="form-control" name="nama_projek" id="namaProjek">
                    @foreach($products as $product)
                        <option value="{{$product->nama_projek}}" data-costumer="{{$product->costumer}}" @if($product->nama_projek == $product->nama_projek)selected @endif>{{$product->nama_projek}}</option>
                    @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <strong>No Invoice</strong>
                    <input type="number" name="no_invoice" class="form-control" placeholder="Nomor Invoice" value="{{ $pengiriman->no_invoice }}">
                </div>
                <div class="form-group">
                    <strong>Termin</strong>
                    <input type="number" name="termin" class="form-control" placeholder="Termin" value="{{$pengiriman->termin}}">
                </div>
                <div class="form-group">
                    <strong>Nominal</strong>
                    <input type="number" name="nominal_projek" class="form-control" placeholder="Nominal" value="{{$pengiriman->nominal_projek}}">
                </div>
                <div class="form-group">
                    <strong>Keterangan</strong>
                    <input type="date" name="keterangan" class="form-control" placeholder="Keterangan" value="{{$pengiriman->keterangan}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="form-group">
                    <strong>Tanggal Kirim</strong>
                    <input type="date" name="tanggal_kirim" class="form-control" placeholder="Tanggal Kirim" value="{{$pengiriman->tanggal_kirim}}">
                </div>
                <div class="form-group">
                    <strong>Costumer</strong>
                    <input type="text" name="costumer" class="form-control" placeholder="Costumer" value="{{$pengiriman->costumer}}" id="costumersInput" readonly>
                </div>
                <div class="form-group">
                    <strong>No Faktur</strong>
                    <input type="number" name="no_faktur" class="form-control" placeholder="NO Faktur" value="{{$pengiriman->no_faktur}}">
                </div>
                <div class="form-group">
                    <strong>Total Invoice</strong>
                    <input type="number" name="total_invoice" class="form-control" placeholder="Total Invoice" value="{{$pengiriman->total_invoice}}">
                </div>
                <div class="form-group">
                    <strong>PPN</strong>
                    <input type="number" name="ppn" class="form-control" placeholder="PPN" value="{{$pengiriman->ppn}}">
                </div>
                <div class="form-group">
                    <strong>Pembayaran</strong>
                    <input type="currency" name="pembayaran" class="form-control" placeholder="Pembayaran" value="{{$pengiriman->pembayaran}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-danger" href="{{ route('pengirimans.index') }}"> Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        
    </form>
@endsection
@section('javascripts')
    <script>
        // code untuk mengisi collum costumer
        let namaProjek = document.getElementById('namaProjek');
        let costumersInput = document.getElementById('costumersInput');

        namaProjek.value = "{{$pengiriman->nama_projek}}";

        namaProjek.addEventListener('change', (e) => {
            // console.log( namaProjek.options[namaProjek.selectedIndex].dataset);
            let costumer = namaProjek.options[namaProjek.selectedIndex].dataset.costumer;
            costumersInput.value=costumer;
        })
    </script> 
@endsection

resources/views/pengirimans/index.blade.php
@extends('layouts.home')

@section('styles')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
@endsection

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Data Invoice</h1>
        <a href="{{ route('pengirimans.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Tambah Invoice</a>
    </div>
    <br>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Table Invoice</h6>
        </div>
        <div class="card-body">
                <table class="display table table-responsive" id="table_id" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tanggal Invoice</th>
                            <th>Tanggal Kirim</th>
                            <th>Costumer</th>
                            <th>Nama Projek</th>
                            <th>No Invoice</th>
                            <th>No Faktur</th>
                            <th>Termin</th>
                            <th>Nominal Pajak</th>
                            <th>PPN</th>
                            <th>Total Invoice</th>
                            <th>Keterangan</th>
                            <th>Pembayaran</th>
                            <th width="280px">action</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($pengirimans as $pengiriman)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $pengiriman->tanggal_invoice }}</td>
                            <td>{{ $pengiriman->tanggal_kirim}}</td>
                            <td>{{ $pengiriman->costumer }}</td>
                            <td>{{ $pengiriman->nama_projek }}</td>
                            <td>{{ $pengiriman->no_invoice }}</td>
                            <td>{{ $pengiriman->no_faktur }}</td>
                            <td>{{ $pengiriman->termin }}</td>
                            <td>{{ $pengiriman->nominal_projek }}</td>
                            <td>{{ $pengiriman->ppn }}</td>
                            <td>{{ $pengiriman->total_invoice }}</td>
                            <td>{{ $pengiriman->keterangan }}</td>
                            <td>{{ $pengiriman->pembayaran }}</td>
                            <td>
                                <a class="btn btn-circle btn-primary" href="{{ route('pengirimans.edit',$pengiriman->id) }}">
                                    <i class="fas fa-edit fa-md"></i></a>
                            </td>
                            <td>
                                <button type="submit" class="btn btn-circle btn-danger" data-toggle="modal" data-target="#deleteModal">
                                    <i class="fas fa-trash fa-md"></i></button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
        </div>
    </div>
    <!-- Delete Modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin ingin menghapus data ini</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Anda tidak akan bisa memulihkan kembali data ini</div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="button" data-dismiss="modal">Cancel</button>
                    @foreach ($pengirimans as $pengiriman)
                        <form action="{{ route('pengirimans.destroy',$pengiriman->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            @endforeach
                            <button type="submit" class="btn btn-danger">
                                Delete
                            </button>
                        </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('javascripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection